openapi: "3.0.3"

info:
  title: API REST VoiceIt
  description: >-
    This API allows you to create new notes by recording your voice and transcribe it.
    Each note is part of a subject that includes multiple notes.
  version: 1.0.0
  contact:
    url: https://github.com/camilleschaller/voiceit

servers:
  - url: https://projet-voiceit.herokuapp.com

paths:
  /users:
    get:
      summary: List users.
      parameters:
      responses:
        200:
          headers:
            Link:
              $ref: '#/components/headers/PaginationLink'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInRequestBody'
      responses:
        201:
          description: The person was successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        422:
          $ref: '#/components/responses/UserValidationError'
    put:
      summary: Modify a user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInRequestBody'
      responses:
        201:
          description: The User was successfully modified.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      summary: Delete a user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInRequestBody'
      responses:
        201:
          description: The User was successfully deleted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /subjects:
    get:
      summary: List subjects.
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        200:
          headers:
            Link:
              $ref: '#/components/headers/PaginationLink'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/subject'
    post:
      summary: Create a subject.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubjectInRequestBody'
      responses:
        201:
          description: The subject was successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subject'
        422:
          $ref: '#/components/responses/SubjectValidationError'
    put:
      summary: Modify a subject.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubjectInRequestBody'
      responses:
        201:
          description: The subject was successfully modified.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subject'
    delete:
      summary: Delete a subject.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubjectInRequestBody'
      responses:
        201:
          description: The Subject was successfully deleted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subject'
  /notes:
    get:
      summary: List notes.
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        200:
          headers:
            Link:
              $ref: '#/components/headers/PaginationLink'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      summary: Create a new note.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteInRequestBody'
      responses:
        201:
          description: The Note was successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
    put:
      summary: Modify a note.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteInRequestBody'
      responses:
        201:
          description: The note was successfully modified.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/note'
    delete:
      summary: Delete a note.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteInRequestBody'
      responses:
        201:
          description: The note was successfully deleted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
components:
  headers:
    PaginationLink:
      description: Links to the first, previous, next and last pages of the collection (if applicable).
      schema:
        type: string
      example: >-
        <https://projet-voiceit.herokuapp.com/api/notes?page=1&pageSize=5>; rel="first prev"
  parameters:
    page:
      name: page
      in: query
      schema:
        type: integer
        min: 1
      example: 1
    pageSize:
      name: pageSize
      in: query
      schema:
        type: integer
        min: 1
        max: 5
      example: 2
  responses:
    UserNotFoundError:
      description: The user does not exist.
      content:
        text/plain: No user found with ID 58b2926f5e1def0123e97bc0.
    UserValidationError:
      description: The user is invalid.
      content:
        application/json:
          example: |-
            {
              "message": "User validation failed",
              "errors": {
                "email": {
                  "kind": "format",
                  "message": "`exemple.ch` is not a valid format value for path `email`.",
                  "name": "ValidatorError",
                  "path": "mail",
                  "properties": {
                    "format": "email",
                    "message": "`{VALUE}` is not a valid format value for path `{PATH}`.",
                    "path": "mail",
                    "type": "format",
                    "value": "exemple.ch"
                  },
                  "value": "exemple.ch"
                }
              }
            }
  schemas:
    User:
      type: object
      properties:
        pseudo:
          type: string
          description: The pseudo of the user (must be unique).
          minlength: 3
          maxlength: 30
          example: JohnDoe
        password:
          type: string
          description: The password of the user.
          example: 'passwordtest'
        mail:
          type: string
          description: The email address of the user. MUST be in the format of an email address.
          example: mail@exemple.com
          format: email
      required:
        - pseudo
        - password
        - mail
      additionalProperties: false
    Subject:
      type: object
      properties:
        title:
          type: string
          description: The title of the subject (must be unique).
          minlength: 1
          maxlength: 20
          example: Mathematics
        description:
          type: string
          description: The description of the subject
          maxlength: 100
          example: This subject includes mathematics.
        userId:
          type: Schema.Types.ObjectId
          description: The id of the person linked.
      required:
        - title
        - userId
      additionalProperties: false
    Note:
      type: object
      properties:
        title:
          type: string
          description: The title of the note (must be unique).
          minlength: 1
          maxlength: 20
          example: Algebra 2
        text:
          type: String
          description: The content of the note.
        imageURL:
          type: String
          description: The image URL of the note.
        createdAt:
          type: Date
          description: When was the note created.
        subectId:
          type: Schema.Types.ObjectId
          description: The id of the subject linked.
      required:
        - title
        - createdAt
        - subjectId
      additionalProperties: false